/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-07-05

 The MIT License (MIT)
 Copyright (c) 2018 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

#include <stddef.h>
#include <stdio.h>

#include "stm32f10x.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"
#include "semphr.h"

#include "uart.h"

static const uint32_t LsiFreq = 40000;

static void hardwareInitialize(void)
{
	if (RCC_GetFlagStatus(RCC_FLAG_IWDGRST) != RESET) {
	    /* IWDGRST flag set, clear reset flags */
	    RCC_ClearFlag();
	}
	/* IWDG timeout equal to 8s (the timeout may varies due to LSI frequency dispersion) */
	/* Enable write access to IWDG_PR and IWDG_RLR registers */
	IWDG_WriteAccessCmd(IWDG_WriteAccess_Enable);
	/* IWDG counter clock: LSI/128 */
	IWDG_SetPrescaler(IWDG_Prescaler_128);

	/* Set counter reload value to obtain 4s IWDG TimeOut.
	   Counter Reload Value = 8s/IWDG counter clock period
						    = 8s / (LSI/128)
						    = 8s / (LsiFreq/128)
						    = LsiFreq / (128 / 8)
						    = LsiFreq / 16
     */
	IWDG_SetReload(LsiFreq/(128 / 8));
	/* Reload IWDG counter */
	IWDG_ReloadCounter();
	/* Enable IWDG (the LSI oscillator will be enabled by hardware) */
	IWDG_Enable();

	RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOC, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1, ENABLE);
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART2, ENABLE);

	/* Configure the NVIC Preemption Priority Bits */
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_4);

	fullDuplexUartInitialize();
	halfDuplexUartInitialize();
}

typedef enum {
	BLINK_PATTERN_DISCONNECTED,
	BLINK_PATTERN_CONNECTED
} BlinkPattern;

static BlinkPattern blinkPattern = BLINK_PATTERN_DISCONNECTED;

#define HEARTBEAT_PERIOD	1260

static void ledTask(void *pvParameters)
{
	uint8_t phase = 0;
	BitAction value;
	portTickType delayTime;

	GPIO_InitTypeDef gpioInitStructure;
	gpioInitStructure.GPIO_Pin = GPIO_Pin_13;
	gpioInitStructure.GPIO_Speed = GPIO_Speed_2MHz;
	gpioInitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_Init(GPIOC, &gpioInitStructure);

	portTickType xNextWakeTime = xTaskGetTickCount();

	for (;;) {
		switch(blinkPattern) {
		case BLINK_PATTERN_DISCONNECTED:
			switch(phase) {
				case 0:
					++phase;
					delayTime = pdMS_TO_TICKS(1200);
					value = Bit_RESET;
					break;
				default:
					phase = 0;
					delayTime = pdMS_TO_TICKS(300);
					value = Bit_SET;
					break;
				}
				break;
			break;
		case BLINK_PATTERN_CONNECTED:
			switch(phase) {
			case 0:
				++phase;
				delayTime = pdMS_TO_TICKS(70);
				value = Bit_RESET;
				break;
			case 1:
				++phase;
				delayTime = pdMS_TO_TICKS(HEARTBEAT_PERIOD/4) - pdMS_TO_TICKS(70);
				value = Bit_SET;
				break;
			case 2:
				++phase;
				delayTime = pdMS_TO_TICKS(70);
				value = Bit_RESET;
				break;
			default:
				phase = 0;
				delayTime = pdMS_TO_TICKS(HEARTBEAT_PERIOD) - pdMS_TO_TICKS(HEARTBEAT_PERIOD/4) - pdMS_TO_TICKS(70);
				value = Bit_SET;
				break;
			}
			break;
		default:
			break;
		}
		GPIO_WriteBit(GPIOC, GPIO_Pin_13, value);
		vTaskDelayUntil(&xNextWakeTime, delayTime);
		/* Reload IWDG counter */
		IWDG_ReloadCounter();
	}
}

static void disconnectTimer(TimerHandle_t xTimer)
{
	blinkPattern = BLINK_PATTERN_DISCONNECTED;
}

static void mainTask(void *pvParameters)
{
	static uint8_t buf[32+1];

	xTaskCreate(ledTask, "LED",
				configMINIMAL_STACK_SIZE,
				NULL,
				1,
				NULL);

	TimerHandle_t timer = xTimerCreate("Timer",
			pdMS_TO_TICKS(3000),
			pdTRUE,
			0,
			disconnectTimer);
	xTimerStart(timer, pdMS_TO_TICKS(10));

	for (;;) {
		int ret = fullDuplexUartRead(buf, 32);
		if (ret > 0) {
			halfDuplexUartWrite(buf, ret);
			blinkPattern = BLINK_PATTERN_CONNECTED;
			xTimerReset(timer, pdMS_TO_TICKS(10));
		}
		ret = halfDuplexUartRead(buf, 32);
		if (ret > 0) {
			fullDuplexUartWrite(buf, ret);
		}
	}
}

int main(void)
{
	hardwareInitialize();

	xTaskCreate(mainTask, "Main",
					configMINIMAL_STACK_SIZE,
					NULL,
					0,
					NULL);

	vTaskStartScheduler();

	return 0;
}

#ifdef  USE_FULL_ASSERT

/**
 * @brief  Reports the name of the source file and the source line number
 *   where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t* file, uint32_t line)
{
	/* User can add his own implementation to report the file name and line number,
	 ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

	/* Infinite loop */
	while (1)
	{
	}
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func,
		const char *failedexpr)
{
	while (1)
	{
	}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
	__assert_func(file, line, NULL, failedexpr);
}

#ifdef USE_SEE
#ifndef USE_DEFAULT_TIMEOUT_CALLBACK
/**
 * @brief  Basic management of the timeout situation.
 * @param  None.
 * @retval sEE_FAIL.
 */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
	/* Return with error code */
	return sEE_FAIL;
}
#endif
#endif /* USE_SEE */
